# Generated by Django 6.0 on 2026-02-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='address_line_1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='address_line_2',
        ),
    ]
