# Generated by Django 6.0 on 2026-02-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(help_text='e.g. Dog, Cat, Bird, Rabbit', max_length=60),
        ),
    ]
